# Generated by Django 5.2.8 on 2025-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('foto', models.URLField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
